version: "2"
services:
    web:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
    mysql:
        image: mysql
        env_file: .env
        environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
    redis:
        image: redis:alpine